2022-10-11 02:52:07,508 INFO    MainThread:11825 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 02:52:07,509 INFO    MainThread:11825 [wandb_setup.py:_flush():75] Loading settings from /content/SSLMemes/wandb/settings
2022-10-11 02:52:07,509 INFO    MainThread:11825 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-10-11 02:52:07,509 INFO    MainThread:11825 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 02:52:07,509 INFO    MainThread:11825 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_025207-2rf1ar3k/logs/debug.log
2022-10-11 02:52:07,509 INFO    MainThread:11825 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_025207-2rf1ar3k/logs/debug-internal.log
2022-10-11 02:52:07,509 INFO    MainThread:11825 [wandb_init.py:init():439] calling init triggers
2022-10-11 02:52:07,510 INFO    MainThread:11825 [wandb_init.py:init():443] wandb.init called with sweep_config: {}
config: {}
2022-10-11 02:52:07,510 INFO    MainThread:11825 [wandb_init.py:init():492] starting backend
2022-10-11 02:52:07,510 INFO    MainThread:11825 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 02:52:07,532 INFO    MainThread:11825 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 02:52:07,550 INFO    MainThread:11825 [backend.py:ensure_launched():225] started backend process with pid: 11901
2022-10-11 02:52:07,554 INFO    MainThread:11825 [wandb_init.py:init():501] backend started and connected
2022-10-11 02:52:07,569 INFO    MainThread:11825 [wandb_init.py:init():565] updated telemetry
2022-10-11 02:52:07,605 INFO    MainThread:11825 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 02:52:15,362 INFO    MainThread:11825 [wandb_run.py:_on_init():1759] communicating current version
2022-10-11 02:52:15,441 INFO    MainThread:11825 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.13.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-11 02:52:15,441 INFO    MainThread:11825 [wandb_init.py:init():625] starting run threads in backend
2022-10-11 02:52:20,003 INFO    MainThread:11825 [wandb_run.py:_console_start():1733] atexit reg
2022-10-11 02:52:20,003 INFO    MainThread:11825 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-10-11 02:52:20,004 INFO    MainThread:11825 [wandb_run.py:_redirect():1611] Redirecting console.
2022-10-11 02:52:20,011 INFO    MainThread:11825 [wandb_run.py:_redirect():1667] Redirects installed.
2022-10-11 02:52:20,012 INFO    MainThread:11825 [wandb_init.py:init():664] run started, returning control to user process
2022-10-11 02:52:35,487 INFO    MainThread:11825 [pyagent.py:run():320] Starting sweep agent: entity=None, project=None, count=5
2022-10-11 02:52:37,026 INFO    Thread-18 :11825 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 02:52:37,026 INFO    Thread-18 :11825 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 02:52:37,026 INFO    Thread-18 :11825 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'sweep_id': 'l6w3bmxp', 'run_id': 'kk315ykx', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-l6w3bmxp/config-kk315ykx.yaml'}
2022-10-11 02:52:37,026 INFO    Thread-18 :11825 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 02:52:37,026 INFO    Thread-18 :11825 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_025237-kk315ykx/logs/debug.log
2022-10-11 02:52:37,027 INFO    Thread-18 :11825 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_025237-kk315ykx/logs/debug-internal.log
2022-10-11 02:52:37,027 INFO    Thread-18 :11825 [wandb_init.py:init():439] calling init triggers
2022-10-11 02:52:37,027 INFO    Thread-18 :11825 [wandb_init.py:init():443] wandb.init called with sweep_config: {'amp': True, 'batch_size': 160, 'dropout': 0.5, 'epochs': 1, 'eval_step': 100, 'hidden_size': 512, 'img_feature_path': 'data/features/visualbert/', 'learning_rate': 0.004483076615585779, 'model_path': 'uclanlp/visualbert-nlvr2-coco-pre', 'model_type': 'visualbert', 'optimizer': 'adam', 'output_dir': './tmp', 'random_seed': 42, 'resume_training': True, 'semi-supervised': True, 'train_csv_path': 'data/splits/random/memotion_train.csv', 'val_csv_path': 'val_csv_path'}
config: {}
2022-10-11 02:52:37,027 INFO    Thread-18 :11825 [wandb_init.py:init():487] wandb.init() called when a run is still active
2022-10-11 02:52:37,028 INFO    Thread-18 :11825 [wandb_run.py:finish():1539] finishing run vietnguyen/meme_experiments/2rf1ar3k
2022-10-11 02:52:37,028 INFO    Thread-18 :11825 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-10-11 02:52:37,031 INFO    Thread-18 :11825 [wandb_run.py:_restore():1674] restore
2022-10-11 02:52:39,065 INFO    Thread-18 :11825 [wandb_run.py:_restore():1674] restore
2022-10-11 02:52:43,029 ERROR   Thread-18 :11825 [wandb_run.py:_atexit_cleanup():1723] Problem finishing run
Traceback (most recent call last):
  File "/content/SSLMemes/src/train.py", line 154, in train
    model_type = config.model_type
AttributeError: 'NoneType' object has no attribute 'model_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1711, in _atexit_cleanup
    self._on_finish()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1811, in _on_finish
    self._console_stop()  # TODO: there's a race here with jupyter console logging
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1751, in _console_stop
    self._restore()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1680, in _restore
    self._err_redir.uninstall()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 754, in uninstall
    _WSCH.remove_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 667, in remove_fd
    self._unregister()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 655, in _unregister
    signal.signal(signal.SIGWINCH, self._old_handler)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
