2022-10-11 02:54:44,241 INFO    MainThread:12436 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 02:54:44,241 INFO    MainThread:12436 [wandb_setup.py:_flush():75] Loading settings from /content/SSLMemes/wandb/settings
2022-10-11 02:54:44,241 INFO    MainThread:12436 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-10-11 02:54:44,241 INFO    MainThread:12436 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 02:54:44,241 INFO    MainThread:12436 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_025444-gdtk779z/logs/debug.log
2022-10-11 02:54:44,241 INFO    MainThread:12436 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_025444-gdtk779z/logs/debug-internal.log
2022-10-11 02:54:44,241 INFO    MainThread:12436 [wandb_init.py:init():439] calling init triggers
2022-10-11 02:54:44,241 INFO    MainThread:12436 [wandb_init.py:init():443] wandb.init called with sweep_config: {}
config: {}
2022-10-11 02:54:44,241 INFO    MainThread:12436 [wandb_init.py:init():492] starting backend
2022-10-11 02:54:44,242 INFO    MainThread:12436 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 02:54:44,256 INFO    MainThread:12436 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 02:54:44,266 INFO    MainThread:12436 [backend.py:ensure_launched():225] started backend process with pid: 12466
2022-10-11 02:54:44,268 INFO    MainThread:12436 [wandb_init.py:init():501] backend started and connected
2022-10-11 02:54:44,277 INFO    MainThread:12436 [wandb_init.py:init():565] updated telemetry
2022-10-11 02:54:44,304 INFO    MainThread:12436 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 02:54:45,286 INFO    MainThread:12436 [wandb_run.py:_on_init():1759] communicating current version
2022-10-11 02:54:45,326 INFO    MainThread:12436 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.13.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-11 02:54:45,327 INFO    MainThread:12436 [wandb_init.py:init():625] starting run threads in backend
2022-10-11 02:54:48,142 INFO    MainThread:12436 [wandb_run.py:_console_start():1733] atexit reg
2022-10-11 02:54:48,144 INFO    MainThread:12436 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-10-11 02:54:48,144 INFO    MainThread:12436 [wandb_run.py:_redirect():1611] Redirecting console.
2022-10-11 02:54:48,147 INFO    MainThread:12436 [wandb_run.py:_redirect():1667] Redirects installed.
2022-10-11 02:54:48,148 INFO    MainThread:12436 [wandb_init.py:init():664] run started, returning control to user process
2022-10-11 02:54:49,225 INFO    MainThread:12436 [pyagent.py:run():320] Starting sweep agent: entity=None, project=None, count=5
2022-10-11 02:54:50,051 INFO    Thread-12 :12436 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 02:54:50,052 INFO    Thread-12 :12436 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 02:54:50,052 INFO    Thread-12 :12436 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'uncategorized', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'sweep_id': 'qwp6ehme', 'run_id': 'es3qbrdi', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-qwp6ehme/config-es3qbrdi.yaml'}
2022-10-11 02:54:50,052 INFO    Thread-12 :12436 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 02:54:50,052 INFO    Thread-12 :12436 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_025450-es3qbrdi/logs/debug.log
2022-10-11 02:54:50,052 INFO    Thread-12 :12436 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_025450-es3qbrdi/logs/debug-internal.log
2022-10-11 02:54:50,052 INFO    Thread-12 :12436 [wandb_init.py:init():439] calling init triggers
2022-10-11 02:54:50,052 INFO    Thread-12 :12436 [wandb_init.py:init():443] wandb.init called with sweep_config: {'amp': True, 'batch_size': 80, 'dropout': 0.3, 'epochs': 1, 'eval_step': 100, 'hidden_size': 256, 'img_feature_path': 'data/features/visualbert/', 'learning_rate': 0.09188388148909347, 'model_path': 'uclanlp/visualbert-nlvr2-coco-pre', 'model_type': 'visualbert', 'optimizer': 'sgd', 'output_dir': './tmp', 'random_seed': 42, 'resume_training': True, 'semi-supervised': True, 'train_csv_path': 'data/splits/random/memotion_train.csv', 'val_csv_path': 'val_csv_path'}
config: {}
2022-10-11 02:54:50,052 INFO    Thread-12 :12436 [wandb_init.py:init():487] wandb.init() called when a run is still active
2022-10-11 02:54:50,053 INFO    Thread-12 :12436 [wandb_run.py:finish():1539] finishing run vietnguyen/meme_experiments/gdtk779z
2022-10-11 02:54:50,053 INFO    Thread-12 :12436 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-10-11 02:54:50,055 INFO    Thread-12 :12436 [wandb_run.py:_restore():1674] restore
2022-10-11 02:54:52,157 INFO    Thread-12 :12436 [wandb_run.py:_restore():1674] restore
2022-10-11 02:54:55,113 ERROR   Thread-12 :12436 [wandb_run.py:_atexit_cleanup():1723] Problem finishing run
Traceback (most recent call last):
  File "/content/SSLMemes/src/train.py", line 154, in train
    model_type = config.model_type
AttributeError: 'NoneType' object has no attribute 'model_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1711, in _atexit_cleanup
    self._on_finish()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1811, in _on_finish
    self._console_stop()  # TODO: there's a race here with jupyter console logging
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1751, in _console_stop
    self._restore()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1680, in _restore
    self._err_redir.uninstall()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 754, in uninstall
    _WSCH.remove_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 667, in remove_fd
    self._unregister()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 655, in _unregister
    signal.signal(signal.SIGWINCH, self._old_handler)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
